<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6zXSb5x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6zXSb5x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6zXSb5x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6zXSb5x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6zXSb5x\App_KernelDevDebugContainer([
    'container.build_hash' => '6zXSb5x',
    'container.build_id' => '17d55e4f',
    'container.build_time' => 1649532711,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6zXSb5x');
