<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLRG5DFS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLRG5DFS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLRG5DFS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLRG5DFS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLRG5DFS\App_KernelDevDebugContainer([
    'container.build_hash' => 'LRG5DFS',
    'container.build_id' => 'b04eb56a',
    'container.build_time' => 1649077934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLRG5DFS');
